FROM gradle:8.5-jdk17 AS builder
WORKDIR /app

# 루트 빌드 설정 파일 복사
COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle

# common-libs 복사
COPY common ./common

# competition-service 소스 복사
COPY apps/api-gateway ./apps/api-gateway

RUN chmod +x gradlew
RUN ./gradlew :apps:api-gateway:clean :apps:api-gateway:build -x test --no-daemon

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /app/apps/api-gateway/build/libs/*.jar app.jar

EXPOSE 8080

ENV JAVA_OPTS="-Xmx384m -XX:MaxMetaspaceSize=256m -XX:+ExitOnOutOfMemoryError"
ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar app.jar"]